# Generated by Django 5.2.1 on 2025-06-02 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="marks",
            field=models.IntegerField(default=0),
        ),
    ]
